import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { Poppins } from 'next/font/google';
import { LeftSideBar } from "./components/LeftSideBar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="font-sans antialiased min-h-full flex flex-col">
        <div className="min-h-screen bg-white rounded-2xl shadow-2xl shadow-gray-500 border-gray-800 flex font-poppins overflow-hidden">

          {/* Column 1: LeftSideBar hamesha yahan rahega */}
          <div className="border-r border-gray-300">
            <LeftSideBar />
          </div>

          {/* Column 2 & 3: Route ke hisaab se yahan render honge */}
          <main className="flex-1 flex">
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}
